config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i(show new create index) do
    collection do
      get 'activate'
    end
    member do 
      get 'remove_admin'
      get 'make_admin'
    end
  end

  resource :session, only: %i(new create destroy)

  resources :bands do
    resources :albums, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :albums, except: %i(new index) do
    resources :tracks, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :tracks, except: %i(new index) do
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :notes, only: %i(create destroy)

  resource :search_results, only: %i(show)
  
  root to: 'sessions#new'
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  ord         :integer          not null
#  album_id    :integer          not null
#  bonus_track :boolean          default(FALSE)
#  lyrics      :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Track < ApplicationRecord
  validates :title, :ord, :album_id, presence: true
  validates :ord, uniqueness: { scope: :album_id }
  validate :ord_greater_than_zero
  
  belongs_to :album,
    foreign_key: :album_id,
    primary_key: :id,
    class_name: :Album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes,
    dependent: :destroy,
    foreign_key: :track_id,
    primary_key: :id,
    class_name: :Note

  has_many :taggings,
    as: :taggable,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :taggable_id,
    class_name: :Tagging

  has_many :tags,
    through: :taggings,
    source: :tag

  private

  def ord_greater_than_zero
    return if self.ord > 0

    errors.add(:ord, "must cannot be less than 1")
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :must_be_logged_in
  before_action :current_user_admin?, except: [:show]
  
  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def update
    @track = Track.find_by(id: params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @track.destroy
    flash[:notice] = ["#{@track.title} has been deleted!"]
    redirect_to album_url(@track.album_id)
  end
  
  def new_tag
    @tagging = Tagging.new
    @track = Track.find_by(id: params[:id])
    render :tag
  end

  def tag
    @track = Track.find_by(id: params[:id])
    @tagging = Tagging.new(taggable_id: params[:id], taggable_type: "Track")
    tag = Tag.find_by(tag: params[:tagging][:tag].downcase)
    if tag
      @tagging.tag_id = tag.id
    else 
      tag = Tag.new(tag: params[:tagging][:tag].downcase)
      if tag.save
        @tagging.tag_id = tag.id
      else
        flash.now[:errors] = tag.errors.full_messages
        redirect_to track_url(params[:id])
        return
      end
    end

    if @tagging.save
      url = params[:tagging]
      redirect_to track_url(params[:id])
    else
      flash.now[:errors] = @tagging.errors.full_messages
      render :tag
    end
  end

  def edit_tags
    @track = Track.includes(:tags).find_by(id: params[:id])
    @taggings = @track.tags
    render :untag
  end

  def untag
    @track = Track.find_by(id: params[:id])
    tag = Tagging.find_by(taggable_id: params[:id], taggable_type: "Track", tag_id: params[:tag_id])
    if tag
      tag.destroy
      flash[:notice] = ["The Tag has been removed"]
      redirect_to track_url(params[:id])
    else
      redirect_to track_url(params[:id])
    end
  end

  private

  def track_params
    params.require(:track).permit(:title, :ord, :album_id, :bonus_track, :lyrics)
  end
end

app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% submit_text = track.persisted? ? "Update track!" : "Add track!" %>
<form class="form" action="<%= action_url %>" method="post">
  <% if track.persisted? %>
    <input type="hidden" name="_method" value="patch"">
  <% end %>
  <%= auth_token %>

  
  <p>
    <label for="track_title">Title</label>
    <input 
      type="text" 
      name="track[title]" 
      id="track_title" 
      value="<%= track.title %>">
  </p>
  
  <p>
    <label for="track_album">Album</label>
    <select name="track[album_id]" id="track_album">
      <option 
        disabled 
        <%= track.album_id ? "" : "selected" %>>--Select an Album--</option>
        <% Album.all.each do |album| %>
          <option 
            value="<%= album.id %>"
            <%= album_selector(track, album) %>
            ><%= album.title %></option>
        <% end %>
    </select>
  </p>


  <p>
    <label for="track_ord">Track Number</label>
    <input 
      type="number" 
      name="track[ord]" 
      id="track_ord" 
      value="<%= track.ord %>">
  </p>
  
  <p>
    <label for="track_regular_button">Standard</label>
    <input 
      type="radio" 
      name="track[bonus_track]" 
      id="track_regular_button" 
      value="false"
      <%= track.bonus_track ? "" : "checked" %>>

    <label for="track_bonus_track_button">Bonus</label>
    <input 
      type="radio" 
      name="track[bonus_track]" 
      id="track_bonus_track_button" 
      value="true"
      <%= track.bonus_track ? "checked" : "" %>>
  </p>
  
  <p>
    <label for="track_lyrics">Lyrics</label>
    <textarea 
      name="track[lyrics]" 
      id="track_lyrics" 
      rows="10" 
      cols="40"
      ><%= track.lyrics %></textarea>
  </p>

  
  
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/tracks/edit.html.erb
<h1 class="page-header">Edit <%= @track.title %></h1>
<%= render 'shared/flashes', types: :errors %>
<%= render 'form', track: @track %>

app/views/tracks/new.html.erb
<h1 class="page-header">New <%=current_album.title%> track</h1>
<%= render 'shared/flashes', types: :errors %>
<%= render 'form', track: @track %>

app/views/tracks/show.html.erb
<h1 class="page-header"><% title = @track.bonus_track ? @track.title + "(Bonus track)" : @track.title %><%= title %></h1>

<%= render 'shared/flashes', types: :notice %>

<%= ugly_lyrics(@track.lyrics) %>

<h4 class="sub-header">New Note</h4>

<%= render 'notes/form', track_id: @track.id %>

<h4 class="sub-header">Notes</h4>

<% @track.notes.each do |note| %>
<%= render 'notes/note', note: note %>
<% end %>

<div class="tags-container">
  <h4 class="tags-header">Tags</h4>
  <ul class="page-links">
    <% tags = @track.tags %>
    <% if !tags.empty? %>
      <% tags.each do |tag| %>
        <%= render 'shared/tags', tag: tag %>
      <% end %>
    <% end %>
  </ul>
</div>

<ul class="tag-links-container">
  <% if current_user.admin %>
    <li><%= link_to 'Add Tags', new_tag_track_url(@track), class: "button" %><li>
    <% if !@track.tags.empty? %>
      <li><%= link_to "Remove Tags", edit_tags_track_url(@track), class: "button" %></li>
    <% end %>
  <% end %>
</ul>

<h4 class="sub-header">Links</h4>

<ul class="page-links">
  <% if current_user.admin %>
    <li><%= link_to "Edit Track", edit_track_url(@track), class: "button" %></li>
    <li><%= button_to "Destroy Track", track_url, method: :delete %></li>
  <% end %>
  <li><%= link_to "Back To #{@track.album.title}", album_url(@track.album_id), class: "button" %></li>
</ul>

app/views/tracks/tag.html.erb
<h4 class="page-header">Add Tags</h4>
<%= render 'shared/flashes', types: :notice %>
<%= render 'shared/flashes', types: :errors %>
<%= render 'shared/tag_form', 
  action_url: tag_track_url %>

<ul class="page-links">
  <li><%= link_to "Back to #{@track.title}", track_url(@track), class: "button" %></li>
</ul>

app/views/tracks/untag.html.erb
<h4 class="page-header">Click a tag to remove</h4>

<ul class="remove-tag-buttons">
  <% @taggings.each do |tag| %>
    <li>
      <%= button_to "#" + tag.tag, 
        untag_track_url + "?tag_id=#{tag.id}", 
        method: :delete %>
      </li>
  <% end %>
</ul>

<ul class="page-links">
  <li><%= link_to "Back to #{@track.title}", track_url(@track), class: "button" %></li>
</ul>