config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i(show new create index) do
    collection do
      get 'activate'
    end
    member do 
      get 'remove_admin'
      get 'make_admin'
    end
  end

  resource :session, only: %i(new create destroy)

  resources :bands do
    resources :albums, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :albums, except: %i(new index) do
    resources :tracks, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :tracks, except: %i(new index) do
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :notes, only: %i(create destroy)

  resource :search_results, only: %i(show)
  
  root to: 'sessions#new'
end

app/views/shared/_errors.html.erb
<% symbol = types == :error ? :errors : :notice %>
<% if flash[symbol] %>
  <% flash[symbol].each do |f| %>
    <pre class="flash"><%= f %></pre>
  <% end %>
<% end %> 

app/views/shared/_flashes.html.erb
<% symbol = types == :errors ? :errors : :notice %>
<% if flash[symbol] %>
  <% flash[symbol].each do |f| %>
    <pre class="flash"><%= f %></pre>
  <% end %>
<% end %> 

app/views/shared/_form.html.erb
<% action_url = log_in ? session_url : users_url %>
<% submit_text = log_in ? "Log in!" : "Sign up!" %>
<% link_text = log_in ? "Go to Sign-up" : "Go to Log in" %>
<% link_url = log_in ? new_user_url : new_session_url %>

<a class="button" href="<%= link_url %>"><%= link_text %></a>

<form class="form" action="<%= action_url %>" method="post">
  <%= auth_token %>
  
  <p>
    <label class="email-label" for="user_email">Email</label>
    <input type="text" name="user[email]" id="user_email">
  </p>

  <p>
    <label for="user_password">Password</label>
    <input type="password" name="user[password]" id="user_password">
  </p>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/shared/_tag_form.html.erb
<form class="form" action="<%= action_url %>" method="post">
  <%= auth_token %>
  <p>
    <label for="tagging_tag">Tag</label>
    <input type="text" name="tagging[tag]" id="tagging_tag">
  </p>

  <input type="submit" value="Add Tag">
</form>

app/views/shared/_tags.html.erb
<li>
  <form class="tags" action="<%= search_results_url %>" method="get">
    <input type="hidden" name="search[search_type]" value="Tag">
    <input type="hidden" name="search[search_input]" value="<%= tag.tag %>">
    <input type="submit" value="#<%= tag.tag %>">
  </form>
</li>