config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i(show new create index) do
    collection do
      get 'activate'
    end
    member do 
      get 'remove_admin'
      get 'make_admin'
    end
  end

  resource :session, only: %i(new create destroy)

  resources :bands do
    resources :albums, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :albums, except: %i(new index) do
    resources :tracks, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :tracks, except: %i(new index) do
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :notes, only: %i(create destroy)

  resource :search_results, only: %i(show)
  
  root to: 'sessions#new'
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true

  belongs_to :band,
    foreign_key: :band_id,
    primary_key: :id,
    class_name: :Band

  has_many :tracks,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Track

  has_many :taggings,
    as: :taggable,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :taggable_id,
    class_name: :Tagging

  has_many :tags,
    through: :taggings,
    source: :tag
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :must_be_logged_in
  before_action :current_user_admin?, except: [:show]
  
  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    flash[:notice] = "#{@album.title} has been deleted!"
    redirect_to band_url(@album.band_id)
  end

  def new_tag
    @tagging = Tagging.new
    @album = Album.find_by(id: params[:id])
    render :tag
  end

  def tag
    @album = Album.find_by(id: params[:id])
    @tagging = Tagging.new(taggable_id: params[:id], taggable_type: "Album")
    tag = Tag.find_by(tag: params[:tagging][:tag].downcase)
    if tag
      @tagging.tag_id = tag.id
    else 
      tag = Tag.new(tag: params[:tagging][:tag].downcase)
      if tag.save
        @tagging.tag_id = tag.id
      else
        flash.now[:errors] = tag.errors.full_messages
        redirect_to album_url(params[:id])
        return
      end
    end

    if @tagging.save
      url = params[:tagging]
      redirect_to album_url(params[:id])
    else
      flash.now[:errors] = @tagging.errors.full_messages
      render :tag
    end
  end

  def edit_tags
    @album = Album.includes(:tags).find_by(id: params[:id])
    @taggings = @album.tags
    render :untag
  end

  def untag
    @album = Album.find_by(id: params[:id])
    tag = Tagging.find_by(taggable_id: params[:id], taggable_type: "Album", tag_id: params[:tag_id])
    if tag
      tag.destroy
      flash[:notice] = ["The Tag has been removed"]
      redirect_to album_url(params[:id])
    else
      redirect_to album_url(params[:id])
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end
end

app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% submit_text = album.persisted? ? "Update Album!" : "Add Album!" %>
<form class="form" action="<%= action_url %>" method="post">
  <% if album.persisted? %>
    <input type="hidden" name="_method" value="patch"">
  <% end %>
  <%= auth_token %>

  <p>
    <label for="album_title">Title:</label>
    <input 
      type="text" 
      name="album[title]" 
      id="album_title" 
      value="<%= album.title %>">
  </p>

  <p>
    <label for="album_band">Band:</label>
    <select name="album[band_id]" id="album_band">
      <option disabled <%= album.band_id ? "" : "selected" %>>--Select a Band--</option>
      <% Band.all.each do |band| %>
        <option 
          value="<%= band.id %>"
          <%= band_selector(album, band) %>
          ><%= band.name %></option>
      <% end %>
    </select>
  </p>


  <p>
    <label for="album_live_button">Live</label>
    <input 
      type="radio" 
      name="album[live]" 
      id="album_live_button" 
      value="true"
      <%= album.live ? "checked" : "" %>>

    <label for="album_studio_button">Studio</label>
    <input 
      type="radio" 
      name="album[live]" 
      id="album_studio_button" 
      value="false"
      <%= album.live ? "" : "checked" %>>
  </p>

  <p>
    <label for="album_year">Year:</label>
    <input 
      type="number" 
      name="album[year]" 
      id="album_year" 
      value="<%= album.year %>">
  </p>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/albums/_tracks.html.erb
<li>
  <a 
    href="<%= track_url(track) %>"><% 
      title = 
      track.bonus_track ? track.title + "(Bonus track)" : track.title 
      %><p><%= title %></p></a>
</li>

app/views/albums/edit.html.erb
<h1 class="page-header">Edit <%= @album.title %>!</h1>
<%= render 'shared/flashes', types: :errors %>
<%= render 'form', album: @album %>

app/views/albums/new.html.erb
<h1 class="page-header">Add a New album</h1>
<%= render 'shared/flashes', types: :errors %>
<%= render 'form', album: @album%>

app/views/albums/show.html.erb
<%= flash[:notice] %>
<h1 class="page-header"><% title = @album.live ? @album.title + "(Live)" : @album.title %><%= title %></h1>

<%= render 'shared/flashes', types: :notice %>

<ul class="main-list">
  <% tracks = @album.tracks %>
  <% if tracks.empty?%>
  <p>This album has no tracks... yet!</p>
  <% else%>
  <% tracks.each do |track| %>
  <%= render 'tracks', track: track %>
  <% end %>
  <% end %>

</ul>

<div class="tags-container">
  <h4 class="tags-header">Tags</h4>
  <ul class="page-links">
    <% tags = @album.tags %>
    <% if !tags.empty? %>
      <% tags.each do |tag| %>
        <%= render 'shared/tags', tag: tag %>
      <% end %>
    <% end %>
  </ul>
</div>

<ul class="tag-links-container">
  <% if current_user.admin %>
    <li><%= link_to 'Add Tags', new_tag_album_url(@album), class: "button" %><li>
    <% if !@album.tags.empty? %>
      <li><%= link_to "Remove Tags", edit_tags_album_url(@album), class: "button" %></li>
    <% end %>
  <% end %>
</ul>

<h4 class="sub-header">Links</h1>
  
  <ul class="page-links">
    <% if current_user.admin %>
    <li><%= link_to 'New Track', new_album_track_url(@album), class: "button" %><li>
    <li><%= link_to "Edit Album", edit_album_url(@album), class: "button" %></li>
    <li><%= button_to "Destroy Album", album_url, method: :delete %></li>
  <% end %>
  <li><%= link_to "Back to #{@album.band.name}", band_url(@album.band_id), class: "button" %></li>
</ul>

app/views/albums/tag.html.erb
<h4 class="page-header">Add Tags</h4>
<%= render 'shared/flashes', types: :notice %>
<%= render 'shared/flashes', types: :errors %>
<%= render 'shared/tag_form', 
  action_url: tag_album_url %>

<ul class="page-links">
  <li><%= link_to "Back to #{@album.title}", album_url(@album), class: "button" %></li>
</ul>

app/views/albums/untag.html.erb
<h4 class="page-header">Click a tag to remove</h4>

<ul class="remove-tag-buttons">
  <% @taggings.each do |tag| %>
    <li>
      <%= button_to "#" + tag.tag, 
        untag_band_url + "?tag_id=#{tag.id}", 
        method: :delete %>
      </li>
  <% end %>
</ul>

<ul class="page-links">
  <li><%= link_to "Back to #{@album.title}", album_url(@album), class: "button" %></li>
</ul>