config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i(show new create index) do
    collection do
      get 'activate'
    end
    member do 
      get 'remove_admin'
      get 'make_admin'
    end
  end

  resource :session, only: %i(new create destroy)

  resources :bands do
    resources :albums, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :albums, except: %i(new index) do
    resources :tracks, only: [:new]
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :tracks, except: %i(new index) do
    member do
      get 'new_tag'
      get 'edit_tags'
      post 'tag'
      delete 'untag'
    end
  end

  resources :notes, only: %i(create destroy)

  resource :search_results, only: %i(show)
  
  root to: 'sessions#new'
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album

  has_many :tracks,
    through: :albums,
    source: :tracks

  has_many :taggings,
    as: :taggable,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :taggable_id,
    class_name: :Tagging

  has_many :tags,
    through: :taggings,
    source: :tag
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :must_be_logged_in
  before_action :current_user_admin?, except: [:show, :index]
  
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.includes(:tags).includes(:albums).find_by(id: params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    
    if @band.save 
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    flash[:notice] = "#{@band.name} has been deleted!"
    redirect_to bands_url
  end

  def new_tag
    @tagging = Tagging.new
    @band = Band.find_by(id: params[:id])
    render :tag
  end

  def tag
    @band = Band.find_by(id: params[:id])
    @tagging = Tagging.new(taggable_id: params[:id], taggable_type: "Band")
    tag = Tag.find_by(tag: params[:tagging][:tag].downcase)
    if tag
      @tagging.tag_id = tag.id
    else 
      tag = Tag.new(tag: params[:tagging][:tag].downcase)
      if tag.save
        @tagging.tag_id = tag.id
      else
        flash.now[:errors] = tag.errors.full_messages
        redirect_to band_url(params[:id])
        return
      end
    end

    if @tagging.save
      url = params[:tagging]
      redirect_to band_url(params[:id])
    else
      flash.now[:errors] = @tagging.errors.full_messages
      render :tag
    end
  end

  def edit_tags
    @band = Band.includes(:tags).find_by(id: params[:id])
    @taggings = @band.tags
    render :untag
  end

  def untag
    @band = Band.find_by(id: params[:id])
    tag = Tagging.find_by(taggable_id: params[:id], taggable_type: "Band", tag_id: params[:tag_id])
    if tag
      tag.destroy
      flash[:notice] = ["The Tag has been removed"]
      redirect_to band_url(params[:id])
    else
      redirect_to band_url(params[:id])
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/views/bands/_album_tr.html.erb
<li>
  <a href="<%= album_url(album) %>"><p><%= album.title %></p></a>
</li>

app/views/bands/_albums.html.erb
<li>
  <a href="<%= album_url(album) %>"><p><%= album.title %></p></a>
</li>

app/views/bands/_band.html.erb
<li>
  <a href="<%= band_url(band) %>"><p><%= band.name %></p></a>
</li>

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% submit_text = band.persisted? ? "Update Band!" : "Add Band!" %>
<form class="form" action="<%= action_url %>" method="post">
  <% if band.persisted? %>
    <input type="hidden" name="_method" value="patch"">
  <% end %>
  <%= auth_token %>

  <p>
    <label for="band_name">Name</label>
    <input type="text" name="band[name]" id="band_name" value="<%= band.name %>">
  </p>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/bands/edit.html.erb
<h1 class="page-header">Edit <%= @band.name %>!</h1>
<%= render 'shared/flashes', types: :errors %>
<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h1 class="page-header">Bands</h1>

<%= render 'shared/flashes', types: :notice %>

<ul class="main-list">
  <% if @bands.empty?%>
    <p>There are no bands... yet!</p>
  <% else%>
    <%= render @bands %>
  <% end %>
</ul>

<% if current_user.admin %>
  <h4 class="sub-header">Links</h4>
  <a class="button" href="<%= new_band_url %>">New Band</a>
<% end %> 

app/views/bands/new.html.erb
<h1 class="page-header">New Band!</h1>
<%= render 'shared/flashes', types: :errors %>
<%= render 'form', band: @band %>

app/views/bands/show.html.erb
<h1 class="page-header"><%= @band.name %></h1>

<%= render 'shared/flashes', types: :notice %>

<h4 class="sub-header">Albums</h1>

<ul class="main-list">
  <% albums = @band.albums %>
  <% if albums.empty?%>
    <p>This band has no albums... yet!</p>
  <% else%>
    <% albums.each do |album| %>
      <%= render 'albums', album: album %>
    <% end %>
  <% end %>
</ul>

<div class="tags-container">
  <h4 class="tags-header">Tags</h4>
  <ul class="page-links">
    <% tags = @band.tags %>
    <% if !tags.empty? %>
      <% tags.each do |tag| %>
        <%= render 'shared/tags', tag: tag %>
      <% end %>
    <% end %>
  </ul>
</div>

<ul class="tag-links-container">
  <% if current_user.admin %>
    <li><%= link_to 'Add Tags', new_tag_band_url(@band), class: "button" %><li>
    <% if !@band.tags.empty? %>
      <li><%= link_to "Remove Tags", edit_tags_band_url(@band), class: "button" %></li>
    <% end %>
  <% end %>
</ul>

<h4 class="sub-header">Links</h1>

<ul class="page-links">
  <% if current_user.admin %>
    <li><%= link_to 'New Album', new_band_album_url(@band), class: "button" %><li>
    <li><%= link_to "Edit Band", edit_band_url(@band), class: "button" %></li>
    <li><%= button_to "Destroy Band", band_url, method: :delete %></li>
  <% end %>
  <li><%= link_to "All Bands", bands_url, class: "button" %></li>
</ul>

app/views/bands/tag.html.erb
<h4 class="page-header">Add Tags</h4>
<%= render 'shared/flashes', types: :notice %>
<%= render 'shared/flashes', types: :errors %>
<%= render 'shared/tag_form', 
  action_url: tag_band_url %>

<ul class="page-links">
  <li><%= link_to "Back to #{@band.name}", band_url(@band), class: "button" %></li>
</ul>

app/views/bands/untag.html.erb
<h4 class="page-header">Click a tag to remove</h4>

<ul class="remove-tag-buttons">
  <% @taggings.each do |tag| %>
    <li>
      <%= button_to "#" + tag.tag, 
        untag_band_url + "?tag_id=#{tag.id}", 
        method: :delete %>
      </li>
  <% end %>
</ul>

<ul class="page-links">
  <li><%= link_to "Back to #{@band.name}", band_url(@band), class: "button" %></li>
</ul>